services:
  - type: web
    name: osrm-backend
    env: docker
    plan: free
    dockerfilePath: ./osrm-backend/Dockerfile.osrm  # ğŸ”§ Sá»­a chá»— nÃ y cho Ä‘Ãºng Ä‘Æ°á»ng dáº«n
    autoDeploy: false
    healthCheckPath: /
    region: singapore
    envVars:
      - key: OSRM_ROUTER_PORT
        value: 5000
    ports:
      - port: 5000
        protocol: http
